ALTER TABLE "Employee" DROP CONSTRAINT "Employee_fk0";
ALTER TABLE "Employee" DROP CONSTRAINT "Employee_fk1";
ALTER TABLE "Employee" DROP CONSTRAINT "Employee_fk2";

ALTER TABLE "Employee-Characteristic" DROP CONSTRAINT "Employee-Characteristic_fk0";
ALTER TABLE "Employee-Characteristic" DROP CONSTRAINT "Employee-Characteristic_fk1";

ALTER TABLE "Actor-Rank" DROP CONSTRAINT "Actor-Rank_fk0";
ALTER TABLE "Actor-Rank" DROP CONSTRAINT "Actor-Rank_fk1";
ALTER TABLE "Actor-Rank" DROP CONSTRAINT "Actor-Rank_fk2";

ALTER TABLE "Show" DROP CONSTRAINT "Show_fk0";
ALTER TABLE "Show" DROP CONSTRAINT "Show_fk1";
ALTER TABLE "Show" DROP CONSTRAINT "Show_fk2";
ALTER TABLE "Show" DROP CONSTRAINT "Show_fk3";
ALTER TABLE "Show" DROP CONSTRAINT "Show_fk4";
ALTER TABLE "Show" DROP CONSTRAINT "Show_fk5";

ALTER TABLE "Author" DROP CONSTRAINT "Author_fk0";

ALTER TABLE "Ticket" DROP CONSTRAINT "Ticket_fk0";

ALTER TABLE "Sale" DROP CONSTRAINT "Sale_fk0";

ALTER TABLE "Repertoire" DROP CONSTRAINT "Repertoire_fk0";

ALTER TABLE "Direction" DROP CONSTRAINT "Direction_fk0";
ALTER TABLE "Direction" DROP CONSTRAINT "Direction_fk1";

ALTER TABLE "Tour" DROP CONSTRAINT "Tour_fk0";
ALTER TABLE "Tour" DROP CONSTRAINT "Tour_fk1";

ALTER TABLE "Role-Characteristic" DROP CONSTRAINT "Role-Characteristic_fk0";
ALTER TABLE "Role-Characteristic" DROP CONSTRAINT "Role-Characteristic_fk1";

ALTER TABLE "Role" DROP CONSTRAINT "Role_fk0";

ALTER TABLE "Subscription" DROP CONSTRAINT "Subscription_fk0";
ALTER TABLE "Subscription" DROP CONSTRAINT "Subscription_fk1";

ALTER TABLE "Ticket-Subscription" DROP CONSTRAINT "Ticket-Subscription_fk0";
ALTER TABLE "Ticket-Subscription" DROP CONSTRAINT "Ticket-Subscription_fk1";

DROP trigger "BI_RANK_ID_RANK";
DROP trigger "BI_EMPLOYEE_ID_EMPLOYEE";
DROP trigger "BI_GENDER_ID_GENDER";
DROP trigger "BI_COMPETITION_ID_COMPETITON";
DROP trigger "BI_CHARACTERISTIC_ID_CHARACTERISTIC";
DROP trigger "BI_EDUCATION_ID_EDUCATION";
DROP trigger "BI_SHOW_ID_SHOW";
DROP trigger "BI_AUTHOR_ID_AUTHOR";
DROP trigger "BI_COUNTRY_ID_COUNTRY";
DROP trigger "BI_GENRE_ID_GENRE";
DROP trigger "BI_AGE_CATEGORY_ID_AGE_CATEGORY";
DROP trigger "BI_TICKET_ID_TICKET";
DROP trigger "BI_REPERTOIRE_ID_PERFORMANCE";
DROP trigger "BI_JOB_TYPES_ID_JOB_TYPE";
DROP trigger "BI_ROLE_ID_ROLE";
DROP trigger "BI_SUBSCRIPTION_ID_SUBSCRIPTION";
DROP trigger "ACTOR-RANK-INSERTION";

DROP TABLE "Rank";
DROP TABLE "Employee";
DROP TABLE "Gender";
DROP TABLE "Employee-Characteristic";
DROP TABLE "Competition";
DROP TABLE "Actor-Rank";
DROP TABLE "Characteristic";
DROP TABLE "Education";
DROP TABLE "Show";
DROP TABLE "Author";
DROP TABLE "Country";
DROP TABLE "Genre";
DROP TABLE "Age_category";
DROP TABLE "Ticket";
DROP TABLE "Sale";
DROP TABLE "Repertoire";
DROP TABLE "Direction";
DROP TABLE "Tour";
DROP TABLE "Job_types";
DROP TABLE "Role-Characteristic";
DROP TABLE "Role";
DROP TABLE "Ticket-Subscription";
DROP TABLE "Subscription";

DROP sequence "RANK_ID_RANK_SEQ";
DROP sequence "EMPLOYEE_ID_EMPLOYEE_SEQ";
DROP sequence "GENDER_ID_GENDER_SEQ";
DROP sequence "COMPETITION_ID_COMPETITON_SEQ";
DROP sequence "CHARACTERISTIC_ID_CHARACTERISTIC_SEQ";
DROP sequence "EDUCATION_ID_EDUCATION_SEQ";
DROP sequence "SHOW_ID_SHOW_SEQ";
DROP sequence "AUTHOR_ID_AUTHOR_SEQ";
DROP sequence "COUNTRY_ID_COUNTRY_SEQ";
DROP sequence "GENRE_ID_GENRE_SEQ";
DROP sequence "AGE_CATEGORY_ID_AGE_CATEGORY_SEQ";
DROP sequence "TICKET_ID_TICKET_SEQ";
DROP sequence "REPERTOIRE_ID_PERFORMANCE_SEQ";
DROP sequence "JOB_TYPES_ID_JOB_TYPE_SEQ";
DROP sequence "ROLE_ID_ROLE_SEQ";
DROP sequence "SUBSCRIPTION_ID_SUBSCRIPTION_SEQ";

COMMIT;